### ISSUE TITLE
README.md needs correction.

### ISSUE THREAD

**Issue by EmadBinAbid** [habib-university/haskell-meet#1]
> To contribute, clone the repository, make a branch and develop it, push the branch, and submit a pull request to merge.

To carry out the mentioned process, you will need to authorise the contributor to work on this repository. The simpler way to contribute is to 'fork' the repository and then submit PRs. I hope the issue here is clear and makes sense. 

@waqarsaleem

**Comment by waqarsaleem** [comment]
Updated README. Thank you for pointing this out.
